languageCode = "en-us"
title = "Culnarra - Cultural Narrative of a City"
DefaultContentLanguage = "jp"
description = ""
#change this to false when on culnarra.com
baseURL = "http://localhost:1313"
#baseURL = "https://kkshmz.github.io/culnarra/"
#canonifyURLs = "true"
defaultContentLanguageInSubdir = "true"

[languages]
    [languages.en]
        languageName = "English"
        title = "My blog"
        contentDir = "content/en"
        weight = "2"
    [languages.jp]
        languageName = "Japanese"
        title = "カルナラプロジェクト"
        contentDir = "content/jp"
        weight = "1"